# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-hello-simulator "ns3.36-hello-simulator-default")
set_tests_properties(ctest-hello-simulator PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;1;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-first "ns3.36-first-default")
set_tests_properties(ctest-first PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;7;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-second "ns3.36-second-default")
set_tests_properties(ctest-second PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;17;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-third "ns3.36-third-default")
set_tests_properties(ctest-third PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;28;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fourth "ns3.36-fourth-default")
set_tests_properties(ctest-fourth PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;40;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-fifth "ns3.36-fifth-default")
set_tests_properties(ctest-fifth PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;46;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-sixth "ns3.36-sixth-default")
set_tests_properties(ctest-sixth PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;57;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
add_test(ctest-seventh "ns3.36-seventh-default")
set_tests_properties(ctest-seventh PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;68;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/tutorial/CMakeLists.txt;0;")
