# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.36-bit-serializer-default")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.36-main-packet-header-default")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.36-main-packet-tag-default")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.36-packet-socket-apps-default")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisions "ns3.36-lollipop-comparisions-default")
set_tests_properties(ctest-lollipop-comparisions PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/network/examples/CMakeLists.txt;0;")
