# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src/wimax/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wimax-ipv4 "ns3.36-wimax-ipv4-default")
set_tests_properties(ctest-wimax-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;1;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-multicast "ns3.36-wimax-multicast-default")
set_tests_properties(ctest-wimax-multicast PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;0;")
add_test(ctest-wimax-simple "ns3.36-wimax-simple-default")
set_tests_properties(ctest-wimax-simple PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/wimax/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;22;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/wimax/examples/CMakeLists.txt;0;")
