# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.36-time-probe-example-default")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;1;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.36-gnuplot-example-default")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.36-double-probe-example-default")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.36-gnuplot-aggregator-example-default")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.36-gnuplot-helper-example-default")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.36-file-aggregator-example-default")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.36-file-helper-example-default")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/stats/examples/CMakeLists.txt;0;")
