# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src/lr-wpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-lr-wpan-data "ns3.36-lr-wpan-data-default")
set_tests_properties(ctest-lr-wpan-data PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-mlme "ns3.36-lr-wpan-mlme-default")
set_tests_properties(ctest-lr-wpan-mlme PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-packet-print "ns3.36-lr-wpan-packet-print-default")
set_tests_properties(ctest-lr-wpan-packet-print PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-phy-test "ns3.36-lr-wpan-phy-test-default")
set_tests_properties(ctest-lr-wpan-phy-test PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-distance-plot "ns3.36-lr-wpan-error-distance-plot-default")
set_tests_properties(ctest-lr-wpan-error-distance-plot PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;19;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-model-plot "ns3.36-lr-wpan-error-model-plot-default")
set_tests_properties(ctest-lr-wpan-error-model-plot PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;26;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/lr-wpan/examples/CMakeLists.txt;0;")
