# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.36-traffic-control-default")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;1;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.36-queue-discs-benchmark-default")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;12;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.36-red-vs-fengadaptive-default")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;24;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.36-red-vs-nlred-default")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;35;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.36-tbf-example-default")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;46;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.36-cobalt-vs-codel-default")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1517;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;56;build_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/examples/traffic-control/CMakeLists.txt;0;")
