# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3.36-tap-csma-default")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3.36-tap-csma-virtual-machine-default")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3.36-tap-wifi-virtual-machine-default")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3.36-tap-wifi-dumbbell-default")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/macros-and-definitions.cmake;1354;add_test;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src/tap-bridge/examples/CMakeLists.txt;0;")
