# CMake generated Testfile for 
# Source directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/src
# Build directory: /home/francis-mutetwa/Documents/Main FIle/trial1/anchor-simulator/ns-3.36/cmake-cache/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("antenna")
subdirs("applications")
subdirs("flow-monitor")
subdirs("internet")
subdirs("netanim")
subdirs("nr")
subdirs("point-to-point")
subdirs("propagation")
subdirs("spectrum")
subdirs("wifi")
subdirs("core")
subdirs("network")
subdirs("stats")
subdirs("bridge")
subdirs("traffic-control")
subdirs("config-store")
subdirs("mobility")
subdirs("wimax")
subdirs("energy")
subdirs("csma")
subdirs("lte")
subdirs("fd-net-device")
subdirs("buildings")
subdirs("virtual-net-device")
subdirs("uan")
subdirs("lr-wpan")
subdirs("wave")
subdirs("point-to-point-layout")
subdirs("internet-apps")
subdirs("test")
